rplidar:
  covMtx:
    - [ 0,0001, 0, 0, 0, 0, 0 ]
    - [ 0, 0,0001, 0, 0, 0, 0 ]
    - [ 0, 0, 0,0001, 0, 0, 0 ]
    - [ 0, 0, 0, 0,0001, 0, 0 ]
    - [ 0, 0, 0, 0, 0,0001, 0 ]
    - [ 0, 0, 0, 0, 0, 0,0001 ]
  clustersNum: 75
  velCo: 25
  trainingRowsNumLimit: 6000
  autoencoder:
    epocs: 100
    batchSize: 32
    latentDim: 3

gps_origin:
  covMtx:
    - [ 2.0e-4, 0, 0, 0, 0, 0 ]
    - [ 0, 2.0e-4, 0, 0, 0, 0 ]
    - [ 0, 0, 4.0e-4, 0, 0, 0 ]
    - [ 0, 0, 0,  0.2  , 0, 0 ]
    - [ 0, 0, 0, 0,  0.2  , 0 ]
    - [ 0, 0, 0, 0, 0,  0.4   ]
  updateRate: 0.01
  clustersNum: 75
  velCo: 25
  trainingRowsNumLimit: 18000

normalScenarioName: normal
testScenarioName: follow
lidarTestScenarioCounterLimit: 6000
targetRobotIds: ["uav1","uav2"]