---
uav1:
  gps_origin:
    clustersNum: 75
    velCo: 25
    updateRate: 0.01
    trainingRowsLimit: 200000
  rplidar:
    clustersNum: 75
    velCo: 25
    trainingRowsLimit: 6000
    autoencoder:
      epocs: 100
      batchSize: 32
      latentDim: 3

---
robot: "uav2"
  sensors:
