normalScenarioName: normal
testScenarioName: follow
lidarTestScenarioCounterLimit: 5300
targetRobotIds: ["uav1","uav2"]
plotUpdateRate: 200
normalScenarioStartTime: 6565

gps_origin:
  covMtx:
    - [ 2.0e-4, 0, 0, 0, 0, 0 ]
    - [ 0, 2.0e-4, 0, 0, 0, 0 ]
    - [ 0, 0, 4.0e-4, 0, 0, 0 ]
    - [ 0, 0, 0,  0.2  , 0, 0 ]
    - [ 0, 0, 0, 0,  0.2  , 0 ]
    - [ 0, 0, 0, 0, 0,  0.4   ]
  updateRate: 10
  clustersNum: 32
  velCo: 1.05
  trainingRowsNumLimit: 360000
  gaussianNoiseVarCo: 0

rplidar:
  covMtx:
    - [ 0,0001, 0, 0, 0, 0, 0 ]
    - [ 0, 0,0001, 0, 0, 0, 0 ]
    - [ 0, 0, 0,0001, 0, 0, 0 ]
    - [ 0, 0, 0, 0,0001, 0, 0 ]
    - [ 0, 0, 0, 0, 0,0001, 0 ]
    - [ 0, 0, 0, 0, 0, 0,0001 ]
  clustersNum: 32
  velCo: 0.5
  trainingRowsNumLimit: 120000
  autoencoder:
    epocs: 200
    batchSize: 32
    latentDim: 3
  updateRate: 20
  gaussianNoiseVarCo: 0